server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
<<<<<<< HEAD
        index  comuna-esportes.html index.html;
        try_files $uri $uri/ =404;
=======
        index  index.html;
        try_files $uri $uri/ /index.html;
>>>>>>> 0666ab4 (adicionado cantainer do nginx)
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
<<<<<<< HEAD
}
=======
}
>>>>>>> 0666ab4 (adicionado cantainer do nginx)
